http://localhost:8000/api/teacher/teams/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwibmFtZSI6IkRyLiBIdW1heXJhdHVsIEVrcmEgSHVtcmEiLCJlbWFpbCI6ImVrcmFodW1heXJhdHVsQGdtYWlsLmNvbSIsInJvbGUiOiJURUFDSEVSIiwiaXNFbWFpbFZlcmlmaWVkIjp0cnVlLCJpYXQiOjE3NTc0NTI1NjQsImV4cCI6MTc2MDA0NDU2NH0.65ZyM61JYqB609_ezXR4PDXILHFGh1RQDj7L1MXAVi0
Content-Type: application/json

